Q1 . Create an array of shape (3,3,3) and find the dimension , size of the array

In [16]:
import numpy as np

In [19]:
s=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
s

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

Q2. Create an identity array , add 100 to the array elements , and then divide it with 3 

In [21]:
s=np.eye(3,3)
s

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
s=s+100
s

array([[201., 200., 200.],
       [200., 201., 200.],
       [200., 200., 201.]])

In [26]:
s=s/3
s

array([[22.33333333, 22.22222222, 22.22222222],
       [22.22222222, 22.33333333, 22.22222222],
       [22.22222222, 22.22222222, 22.33333333]])